export interface FreelancePlatform {
  slug: string; name: string; description: string; website: string;
  type: string; categories: string[]; regions: string[]; pricing: "Gratis" | "Freemium" | "Berbayar";
  pricingNote: string; opportunityTypes: string[]; experienceLevels: string[];
  personallyTested: boolean; status: string; lastCheckedAt: string;
  howItWorks: string; forWhom: string; pros: string[]; considerations: string[];
  startSteps: string[]; notes: string; sources: { label: string; url: string }[];
}
type Seed = Pick<FreelancePlatform, "slug" | "name" | "description" | "website" | "type" | "categories" | "pricing" | "pricingNote" | "opportunityTypes" | "howItWorks" | "forWhom" | "pros" | "considerations"> & { source: string };
function platform(seed: Seed): FreelancePlatform {
  const { source, ...data } = seed;
  return { ...data, regions: ["Internasional"], experienceLevels: ["Beragam"], personallyTested: false,
    status: "Belum dicoba", lastCheckedAt: "2026-10-02",
    startSteps: ["Buka situs resmi dan baca ketentuan terbaru.", `Siapkan contoh karya yang relevan dengan ${seed.categories.slice(0, 2).join(" atau ").toLowerCase()}.`, "Periksa lokasi, biaya, dan persyaratan setiap peluang sebelum mengirim aplikasi."],
    notes: "Ringkasan berdasarkan informasi publik dari platform, bukan pengalaman penggunaan langsung atau jaminan diterima. Cakupan internasional tidak berarti setiap peluang menerima pelamar dari Indonesia. Level mengikuti persyaratan masing-masing listing.",
    sources: [{ label: "Informasi resmi platform", url: source }, ...(source !== seed.website ? [{ label: "Situs resmi & cara kerja", url: seed.website }] : [])] };
}
export const FREELANCE_PLATFORMS: FreelancePlatform[] = [
  platform({ slug: "we-work-remotely", name: "We Work Remotely", website: "https://weworkremotely.com", type: "Remote Job Board", categories: ["Development", "Design", "Marketing", "Customer Support"], pricing: "Freemium", pricingNote: "Basic gratis untuk menjelajah dan menyimpan. Aplikasi tanpa batas memerlukan Pro; sebagian listing mengizinkan aplikasi langsung. Periksa komitmen dan pembaruan langganan.", opportunityTypes: ["Full-time", "Contract"], description: "Papan peluang remote lintas bidang dengan filter wilayah dan kategori.", howItWorks: "Buat akun, pilih wilayah dan kategori, lalu baca persyaratan dan jalur aplikasi pada listing.", forWhom: "Pencari peran remote yang siap menyaring batasan negara dan zona waktu.", pros: ["Kategori remote yang mudah ditelusuri.", "Preferensi wilayah membantu mempersempit pencarian."], considerations: ["Remote tetap dapat dibatasi negara atau zona waktu.", "Akses aplikasi bergantung pada listing dan paket akun."], source: "https://weworkremotely.com/frequently-asked-questions" }),
  platform({ slug: "contra", name: "Contra", website: "https://contra.com", type: "Freelance Platform", categories: ["Design", "Development", "Writing", "Marketing"], pricing: "Freemium", pricingNote: "Ada paket Free dan Pro. Klaim tanpa komisi tidak berarti semua transaksi bebas biaya: pembayaran client, metode pencairan, dan penyedia pembayaran dapat dikenai biaya.", opportunityTypes: ["Freelance", "Contract"], description: "Profil karya, peluang independen, kontrak, dan pembayaran dalam satu platform.", howItWorks: "Tampilkan proyek di profil, temukan peluang kontrak, dan kelola kesepakatan serta pembayaran melalui platform.", forWhom: "Profesional independen yang ingin menjadikan karya sebagai titik awal percakapan client.", pros: ["Profil berorientasi karya.", "Kontrak dan pembayaran tersedia dalam alur yang sama."], considerations: ["Peluang dan visibilitas berbeda antara Free dan Pro.", "Baca biaya transaksi serta pencairan sesuai metode yang dipakai."], source: "https://contra.com/pricing" }),
  platform({ slug: "problogger", name: "ProBlogger", website: "https://problogger.com/jobs/", type: "Writing Job Board", categories: ["Writing", "Marketing"], pricing: "Gratis", pricingNote: "Menelusuri job board tersedia gratis. Ketentuan kontrak dan pembayaran ditentukan pemberi kerja.", opportunityTypes: ["Freelance", "Contract"], description: "Job board khusus penulisan blog, konten, dan kebutuhan editorial.", howItWorks: "Cari brief penulisan lalu ikuti petunjuk aplikasi dari pengiklan; kontrak dibuat dengan pemberi kerja.", forWhom: "Writer yang memiliki sampel tulisan dan mampu menilai kecocokan niche serta brief.", pros: ["Fokus penulisan memudahkan pencarian niche.", "Brief dapat menjadi bahan riset kebutuhan pasar."], considerations: ["Kualitas brief dan anggaran berbeda-beda.", "Periksa identitas pengiklan, hak atas karya, dan ketentuan revisi."], source: "https://problogger.com/jobs/" }),
  platform({ slug: "upwork", name: "Upwork", website: "https://www.upwork.com", type: "Freelance Platform", categories: ["Development", "Design", "Writing", "Marketing", "Data"], pricing: "Freemium", pricingNote: "Akun dasar tersedia; banyak proposal memakai Connects. Pendapatan kontrak dikenai service fee sesuai ketentuan yang ditampilkan platform.", opportunityTypes: ["Freelance", "Contract"], description: "Marketplace proyek dengan proposal, kontrak per jam, dan proyek berbasis milestone.", howItWorks: "Lengkapi profil, pilih proyek, kirim proposal dengan Connects bila diperlukan, lalu sepakati kontrak.", forWhom: "Freelancer yang siap menulis proposal spesifik dan menghitung biaya akuisisi client.", pros: ["Model kontrak per jam dan fixed-price.", "Banyak kategori jasa dalam satu marketplace."], considerations: ["Connects tidak menjamin proposal dibaca atau diterima.", "Hitung service fee sebelum menyepakati rate."], source: "https://support.upwork.com/hc/en-us/articles/211062898-Understanding-and-using-Connects" }),
  platform({ slug: "fiverr", name: "Fiverr", website: "https://www.fiverr.com", type: "Freelance Platform", categories: ["Design", "Writing", "Development", "Marketing"], pricing: "Freemium", pricingNote: "Freelancer menerima 80% nilai pesanan menurut halaman Earnings resmi. Periksa biaya pencairan dan program tambahan.", opportunityTypes: ["Freelance"], description: "Marketplace jasa yang dikemas sebagai offer atau Gig dengan lingkup yang jelas.", howItWorks: "Publikasikan Gig, jelaskan deliverable dan paket, lalu kerjakan pesanan sesuai kesepakatan.", forWhom: "Freelancer dengan layanan yang bisa dikemas menjadi paket terukur.", pros: ["Format Gig membantu memperjelas scope.", "Paket jasa dapat menampilkan beberapa pilihan deliverable."], considerations: ["Potongan pendapatan harus masuk perhitungan harga.", "Tentukan batas revisi dan detail paket dengan teliti."], source: "https://help.fiverr.com/hc/en-us/articles/9234443621137-Your-earnings-page" }),
  platform({ slug: "peopleperhour", name: "PeoplePerHour", website: "https://www.peopleperhour.com", type: "Freelance Platform", categories: ["Design", "Development", "Writing", "Marketing"], pricing: "Freemium", pricingNote: "Pendaftaran, pencarian proyek, dan publikasi offer tanpa biaya. Service fee dikenakan pada pendapatan; cek tarif resmi sebelum menetapkan harga.", opportunityTypes: ["Freelance", "Contract"], description: "Marketplace proyek dan offer untuk jasa per jam maupun per proyek.", howItWorks: "Bangun profil, kirim proposal proyek atau publikasikan offer, dan gunakan WorkStream untuk komunikasi proyek.", forWhom: "Freelancer yang ingin menggabungkan proposal custom dan paket jasa.", pros: ["Pilihan proposal dan offer.", "Percakapan serta riwayat proyek dalam WorkStream."], considerations: ["Service fee memengaruhi pendapatan bersih.", "Periksa kebijakan offer dan proses penerimaan profil."], source: "https://support.peopleperhour.com/hc/en-us/articles/205218337-Freelancer-commission-fees" }),
  platform({ slug: "remote-ok", name: "Remote OK", website: "https://remoteok.com", type: "Remote Job Board", categories: ["Development", "Design", "Marketing", "Customer Support"], pricing: "Freemium", pricingNote: "Ada listing dan feed publik, serta fitur Premium dan TopAccess. Detail akses dan biaya perlu diperiksa pada FAQ resmi.", opportunityTypes: ["Full-time", "Contract"], description: "Papan pekerjaan dengan tag skill, lokasi, dan kategori remote.", howItWorks: "Saring tag dan lokasi, baca deskripsi lengkap, lalu ikuti tautan aplikasi perusahaan.", forWhom: "Pencari kerja yang ingin menelusuri peran berdasarkan skill teknis atau fungsi kerja.", pros: ["Tag skill untuk penelusuran cepat.", "Informasi lokasi pada listing."], considerations: ["Sebagian informasi atau fitur berada di paket berbayar.", "Selalu verifikasi listing pada situs perusahaan."], source: "https://remoteok.com/faq" }),
  platform({ slug: "remotive", name: "Remotive", website: "https://remotive.com", type: "Remote Job Board", categories: ["Development", "Design", "Marketing", "Customer Support"], pricing: "Berbayar", pricingNote: "Akses pencarian penuh berbayar; informasi publik dapat terbatas. Baca paket dan aturan langganan terbaru sebelum membayar.", opportunityTypes: ["Full-time", "Contract"], description: "Pencarian pekerjaan remote dengan kategori dan informasi lokasi.", howItWorks: "Cari peran yang sesuai dan ikuti tautan aplikasi ke halaman karier perusahaan.", forWhom: "Pencari kerja yang bersedia membayar akses kurasi dan memeriksa kecocokan lokasi.", pros: ["Kategori dan lokasi membantu pencarian.", "Aplikasi diarahkan ke perusahaan."], considerations: ["Langganan tidak menjamin pekerjaan.", "Waspadai pihak yang mengatasnamakan Remotive melalui pesan pribadi."], source: "https://support.remotive.com/en/article/frequently-asked-questions-180nrek/" }),
  platform({ slug: "flexjobs", name: "FlexJobs", website: "https://www.flexjobs.com", type: "Flexible Job Board", categories: ["Writing", "Development", "Marketing", "Customer Support"], pricing: "Berbayar", pricingNote: "Akses penuh memakai langganan. Paket percobaan dapat berlanjut otomatis; periksa harga, periode, dan pembatalannya.", opportunityTypes: ["Full-time", "Part-time", "Contract"], description: "Peluang remote, hybrid, dan kerja fleksibel dengan akses berlangganan.", howItWorks: "Pilih paket lalu saring pekerjaan berdasarkan kebutuhan; baca lokasi dan model kerja setiap listing.", forWhom: "Pencari kerja yang mempertimbangkan remote maupun jadwal fleksibel.", pros: ["Mencakup beberapa model kerja fleksibel.", "Platform menyatakan melakukan penyaringan listing."], considerations: ["Tidak semua pekerjaan sepenuhnya remote.", "Perhatikan pembaruan otomatis dan total biaya langganan."], source: "https://www.flexjobs.com/pricing" }),
  platform({ slug: "wellfound", name: "Wellfound", website: "https://wellfound.com", type: "Startup Job Board", categories: ["Development", "Product", "Design", "Marketing"], pricing: "Gratis", pricingNote: "Membuat profil dan melamar gratis untuk kandidat menurut FAQ resmi.", opportunityTypes: ["Full-time"], description: "Peluang startup dan teknologi dengan profil kandidat serta informasi kompensasi.", howItWorks: "Buat profil, tetapkan preferensi peran dan lokasi, lalu kirim aplikasi ke startup yang sesuai.", forWhom: "Kandidat yang ingin bekerja di lingkungan startup dan menilai tahap serta kebutuhan tim.", pros: ["Profil dapat digunakan untuk beberapa aplikasi.", "Informasi salary dan equity pada banyak listing."], considerations: ["Pekerjaan remote dan on-site bercampur.", "Kebutuhan serta risiko startup berbeda menurut tahap perusahaan."], source: "https://wellfound.com/candidates/overview" }),
  platform({ slug: "himalayas", name: "Himalayas", website: "https://himalayas.app", type: "Remote Job Board", categories: ["Development", "Design", "Marketing", "Customer Support"], pricing: "Freemium", pricingNote: "Profil, browsing, dan aplikasi gratis. Plus dan Max menawarkan fitur tambahan berbayar.", opportunityTypes: ["Full-time", "Contract"], description: "Pencarian remote dengan preferensi negara, zona waktu, dan profil perusahaan.", howItWorks: "Tetapkan lokasi serta preferensi, cari listing, dan gunakan profil atau petunjuk aplikasi perusahaan.", forWhom: "Pencari kerja yang perlu menyaring kesesuaian zona waktu dan negara sejak awal.", pros: ["Filter negara dan zona waktu.", "Fitur dasar pencarian dan aplikasi gratis."], considerations: ["Fitur AI tertentu memerlukan paket tambahan.", "Keputusan hiring berada pada perusahaan, bukan platform."], source: "https://himalayas.app/docs/what-is-himalayas" }),
  platform({ slug: "working-nomads", name: "Working Nomads", website: "https://www.workingnomads.com/jobs", type: "Remote Job Board", categories: ["Development", "Design", "Marketing", "Data"], pricing: "Freemium", pricingNote: "Listing publik gratis; Premium membuka lebih banyak listing, filter, dan alert.", opportunityTypes: ["Full-time", "Part-time", "Contract"], description: "Kurasi peluang remote lintas fungsi dengan pilihan alert dan akses Premium.", howItWorks: "Jelajahi listing publik berdasarkan kategori atau gunakan fitur Premium jika diperlukan.", forWhom: "Pencari peran remote yang ingin menata pencarian berdasarkan fungsi kerja.", pros: ["Kategori lintas fungsi.", "Listing publik tersedia sebelum berlangganan."], considerations: ["Sebagian listing dan filter berada di Premium.", "Periksa negara yang diterima pada setiap peran."], source: "https://www.workingnomads.com/premium-subscription" }),
  platform({ slug: "jobspresso", name: "Jobspresso", website: "https://jobspresso.co", type: "Remote Job Board", categories: ["Development", "Marketing", "Customer Support"], pricing: "Gratis", pricingNote: "Gratis bagi pencari kerja menurut FAQ resmi.", opportunityTypes: ["Full-time", "Contract"], description: "Job board remote untuk peran teknologi, marketing, dan support.", howItWorks: "Telusuri kategori pekerjaan lalu ikuti petunjuk aplikasi; profil resume juga tersedia.", forWhom: "Pencari kerja yang ingin menelusuri board remote tanpa langganan kandidat.", pros: ["Akses gratis bagi pencari kerja.", "Platform menyatakan meninjau pengiklan dan listing."], considerations: ["Zona waktu atau kunjungan kantor tetap dapat disyaratkan.", "Periksa keaktifan listing sebelum melamar."], source: "https://jobspresso.co/faq/" }),
  platform({ slug: "behance-jobs", name: "Behance Jobs", website: "https://www.behance.net/joblist", type: "Creative Job Board", categories: ["Design", "Writing"], pricing: "Freemium", pricingNote: "Browsing dan aplikasi full-time gratis. Aplikasi freelance memerlukan Behance Pro menurut pembaruan job board Juni 2026.", opportunityTypes: ["Full-time", "Freelance"], description: "Peluang kreatif yang terhubung dengan ekosistem portfolio Behance.", howItWorks: "Gunakan portfolio, saring bidang kreatif dan lokasi, lalu cek jalur aplikasi serta kebutuhan Pro.", forWhom: "Profesional kreatif dengan portfolio visual yang sudah siap ditampilkan.", pros: ["Portfolio dan peluang kreatif saling terhubung.", "Filter freelance, full-time, dan lokasi."], considerations: ["Remote, hybrid, dan on-site bercampur.", "Aplikasi freelance memerlukan paket Pro."], source: "https://www.behance.net/blog/new-job-board" }),
  platform({ slug: "yc-work-at-a-startup", name: "YC Work at a Startup", website: "https://www.ycombinator.com/jobs/", type: "Startup Job Board", categories: ["Development", "Product", "Design", "Marketing"], pricing: "Gratis", pricingNote: "Listing dapat ditelusuri secara publik. Periksa ketentuan akun kandidat pada situs resmi.", opportunityTypes: ["Full-time"], description: "Pencarian pekerjaan di perusahaan dalam ekosistem Y Combinator.", howItWorks: "Cari perusahaan dan peran, periksa lokasi, lalu gunakan profil kandidat atau jalur aplikasi yang tersedia.", forWhom: "Kandidat yang ingin mempelajari kebutuhan tim startup dalam ekosistem YC.", pros: ["Fokus pada ekosistem perusahaan YC.", "Profil kandidat dapat dipakai untuk menjelajahi peluang."], considerations: ["Tidak semua peran remote.", "Syarat lokasi dan pengalaman mengikuti perusahaan."], source: "https://www.ycombinator.com/jobs/" }),
];
export const FEATURED_PLATFORMS = FREELANCE_PLATFORMS.slice(0, 3);
