export interface PlatformEditorial {
  longDescription: string;
  model: string;
  opportunityMethod: string;
  workflow: [string, string, string];
  workingNotes: string;
  tips: string[];
  indonesiaNotes: string[];
  alternativePlatformSlugs: string[];
}

// Editorial guidance is separate from verified platform facts and personal experience.
const details: Record<string, [string, string, string, [string, string, string], string, string[], string[]]> = {
  "we-work-remotely": ["Listing remote", "Baca listing → aplikasi", "WWR menjadi titik awal untuk menemukan perusahaan, bukan pihak yang otomatis mempekerjakanmu. Tag wilayah dan jenis listing menentukan apakah sebuah peluang layak ditindaklanjuti.", ["Pilih wilayah", "Periksa listing", "Kirim aplikasi"], "Jalur aplikasi dapat menuju ATS perusahaan atau email. Siapkan CV untuk peran tertentu; akun atau langganan tidak menggantikan proses seleksi perusahaan.", ["Baca syarat lokasi sebelum menyiapkan aplikasi panjang.", "Pisahkan listing yang bisa diakses Basic dari peluang yang memerlukan paket tambahan."], ["himalayas", "remote-ok", "nodesk"]],
  contra: ["Portfolio & kontrak", "Profil → discovery / aplikasi", "Contra menghubungkan presentasi karya dengan kegiatan bisnis freelance. Profil yang menjelaskan kontribusi dan hasil proyek lebih membantu daripada galeri tanpa konteks.", ["Tampilkan karya", "Temukan kecocokan", "Sepakati kontrak"], "Peluang dapat berawal dari profil maupun pencarian kontrak. Tetap jelaskan scope, jadwal, dan pembayaran sebelum memulai; profil yang lengkap tidak menjamin inbound client.", ["Susun studi kasus dengan masalah, peran, dan hasil yang bisa dibuktikan.", "Periksa total biaya transaksi dan pencairan, bukan hanya istilah tanpa komisi."], ["upwork", "fiverr", "peopleperhour"]],
  problogger: ["Listing penulisan", "Sampel → aplikasi brief", "ProBlogger membantu writer membaca kebutuhan editorial yang nyata. Ia berfungsi sebagai papan pengiklan: kesepakatan mengenai rate, hak publikasi, dan pembayaran perlu dibahas dengan pemberi kerja.", ["Pilih niche", "Cocokkan sampel", "Tanggapi brief"], "Ikuti instruksi aplikasi masing-masing iklan. Sampel tulisan relevan dengan niche dapat menjawab kebutuhan pengiklan lebih langsung daripada mengirim banyak tautan yang tidak terkait.", ["Siapkan dua sampel yang paling dekat dengan topik brief.", "Tanyakan jumlah revisi, byline, dan hak penggunaan sebelum menerima assignment."], ["upwork", "flexjobs", "contra"]],
  upwork: ["Proposal & milestone", "Proposal → kontrak", "Upwork mempertemukan kebutuhan proyek dengan proposal freelancer. Kontrak hourly dan fixed-price memiliki alur pencatatan atau milestone yang berbeda, sehingga model kerja perlu dipilih sebelum menetapkan harga.", ["Pilih proyek", "Tulis proposal", "Sepakati milestone"], "Proposal membutuhkan alasan spesifik mengapa kamu cocok untuk brief. Perhatikan penggunaan Connects, aturan komunikasi, serta ketentuan perlindungan pembayaran; membaca listing saja belum berarti mendapat kontrak.", ["Buka proposal dengan kebutuhan client dan contoh pekerjaan relevan.", "Untuk fixed-price, tentukan deliverable dan persetujuan setiap milestone sebelum mulai."], ["fiverr", "contra", "freelancer"]],
  fiverr: ["Gig / paket jasa", "Publikasikan Gig → pesanan", "Fiverr menempatkan jasa sebagai produk yang dapat dipahami sebelum dipesan. Nama Gig, contoh hasil, paket, dan batas revisi bekerja bersama untuk menjelaskan apa yang dibeli client.", ["Rancang paket", "Publikasikan Gig", "Kerjakan pesanan"], "Client menilai Gig dan profil sebelum menghubungi atau memesan. Karena lingkup jasa sudah ditawarkan di muka, kebutuhan di luar paket perlu dibicarakan secara jelas agar tidak berubah menjadi pekerjaan tambahan tanpa batas.", ["Mulai dari satu deliverable yang bisa dijelaskan dalam satu kalimat.", "Hitung harga bersih setelah potongan dan jelaskan input yang harus dikirim client."], ["upwork", "contra", "peopleperhour"]],
  peopleperhour: ["Proposal & offer", "Bid proyek / publish offer", "PeoplePerHour menyediakan dua pintu masuk: proposal untuk brief custom dan offer untuk jasa yang sudah dikemas. Keduanya memerlukan profil serta kesepakatan kerja yang jelas.", ["Rapikan profil", "Proposal / offer", "Kelola WorkStream"], "Gunakan proposal saat kebutuhan perlu dirancang bersama client; gunakan offer saat deliverable dapat distandardisasi. Pahami aturan penerimaan profil dan komunikasi proyek sebelum mengandalkan platform sebagai kanal utama.", ["Bedakan paket offer dari estimasi proyek custom.", "Periksa fee sesuai hubungan dengan client sebelum mengirim penawaran."], ["upwork", "fiverr", "contra"]],
  "remote-ok": ["Listing dengan tag", "Filter skill → aplikasi", "Remote OK menyajikan listing melalui tag skill dan lokasi. Gunakan board untuk menemukan peran, lalu cek deskripsi serta jalur aplikasi resmi perusahaan sebelum mengirim data.", ["Pilih skill", "Cek negara", "Buka aplikasi"], "Aplikasi mengikuti proses perusahaan pada listing. Tag remote berguna untuk pencarian awal, tetapi lokasi, senioritas, dan zona waktu di deskripsi tetap menjadi acuan.", ["Cari kombinasi skill dan lokasi, bukan hanya kata remote.", "Bandingkan isi listing dengan halaman karier perusahaan."], ["we-work-remotely", "nodesk", "working-nomads"]],
  remotive: ["Kurasi berlangganan", "Cari peran → aplikasi", "Remotive menyusun peluang remote berdasarkan kategori dan lokasi. Nilai langganannya perlu dinilai dari kebutuhan pencarianmu, bukan dari harapan bahwa membayar akan mempersingkat seleksi.", ["Evaluasi akses", "Saring lokasi", "Lamar ke perusahaan"], "Setelah menemukan peran, aplikasi diarahkan ke perusahaan. Pisahkan biaya akses board dari proses seleksi: keputusan hiring dan syarat pekerjaan berada di pihak pemberi kerja.", ["Baca paket dan masa langganan sebelum membayar.", "Pilih kategori dan negara yang benar-benar sesuai dengan profilmu."], ["nodesk", "himalayas", "we-work-remotely"]],
  flexjobs: ["Kerja fleksibel", "Langganan → filter → aplikasi", "FlexJobs mencakup remote, hybrid, serta beberapa bentuk kerja fleksibel. Baca model kerja secara terpisah dari jadwal: jam fleksibel belum tentu berarti bisa bekerja dari negara mana pun.", ["Tentukan kebutuhan", "Pilih filter", "Cek persyaratan"], "Pencarian penuh terkait paket akses. Seleksi dan kontrak tetap mengikuti perusahaan, sehingga penting untuk menilai kecocokan listing sebelum memperpanjang langganan.", ["Pisahkan kebutuhan remote penuh, hybrid, dan part-time.", "Catat tanggal pembaruan paket serta aturan pembatalan."], ["remotive", "working-nomads", "nodesk"]],
  wellfound: ["Hiring startup", "Profil kandidat → aplikasi", "Wellfound menghubungkan kandidat dengan perusahaan startup. Selain deskripsi peran, konteks tim, tahap perusahaan, serta salary dan equity yang dicantumkan membantu memahami bentuk pekerjaannya.", ["Buat profil", "Pelajari startup", "Kirim aplikasi"], "Lengkapi profil untuk peran yang dituju dan teliti kebutuhan tim. Informasi kompensasi pada listing membantu percakapan awal, tetapi paket akhir dan kelayakan kerja perlu dikonfirmasi dengan perusahaan.", ["Jelaskan kontribusi yang ingin kamu bawa ke tahap perusahaan tersebut.", "Tanyakan tanggung jawab, tahap pendanaan, dan detail kompensasi saat interview."], ["yc-work-at-a-startup", "arc", "linkedin-jobs"]],
  himalayas: ["Listing & zona waktu", "Preferensi negara → aplikasi", "Himalayas membantu menelusuri pekerjaan remote dengan preferensi negara dan zona waktu. Informasi perusahaan memberi konteks tambahan sebelum kamu memilih peran untuk dilamar.", ["Atur preferensi", "Cek perusahaan", "Kirim aplikasi"], "Profil dan fitur dasar dapat digunakan untuk pencarian awal. Paket tambahan mendukung fitur tertentu, tetapi tidak mengubah syarat hiring di listing.", ["Hitung jam overlap yang realistis dari WIB, WITA, atau WIT.", "Gunakan filter negara sebelum menelusuri banyak role."], ["we-work-remotely", "nodesk", "remote-ok"]],
  "working-nomads": ["Kurasi lintas fungsi", "Kategori → listing → aplikasi", "Working Nomads mengumpulkan peluang remote lintas fungsi. Listing publik dapat dipakai untuk mempelajari pola kebutuhan, sementara fitur tambahan berada di Premium.", ["Pilih fungsi kerja", "Baca lokasi", "Ikuti aplikasi"], "Setiap listing memiliki jalur dan ketentuan aplikasi sendiri. Gunakan kategori untuk membatasi pencarian dan pastikan peluang masih aktif pada sumber perusahaan.", ["Pilih satu fungsi utama agar pencarian tidak melebar terlalu jauh.", "Cek batas negara dan status listing sebelum menyusun cover letter."], ["nodesk", "remote-ok", "jobspresso"]],
  jobspresso: ["Listing remote", "Pilih kategori → aplikasi", "Jobspresso menampilkan pekerjaan remote untuk beberapa fungsi, terutama teknologi, marketing, dan support. Platform menyatakan meninjau listing; kandidat tetap perlu memeriksa kecocokan perusahaan secara mandiri.", ["Pilih kategori", "Baca kebutuhan", "Lamar resmi"], "Aplikasi mengikuti petunjuk listing atau perusahaan. Tidak ada jaminan semua posisi menerima kandidat lintas negara, walaupun board berfokus pada pekerjaan remote.", ["Periksa jam kerja dan kemungkinan kunjungan kantor.", "Cocokkan pengalamanmu dengan tanggung jawab, bukan hanya judul peran."], ["nodesk", "we-work-remotely", "himalayas"]],
  "behance-jobs": ["Portfolio kreatif", "Portfolio → listing kreatif", "Behance Jobs menghubungkan pencarian pekerjaan dengan portfolio kreatif. Job board mencampur full-time dan freelance; kebutuhan Pro berbeda menurut jenis aplikasi.", ["Kurasi portfolio", "Pilih jenis kerja", "Cek jalur aplikasi"], "Susun karya sesuai kebutuhan peran, lalu baca lokasi dan akses aplikasi. Portfolio yang kuat membantu menunjukkan proses, tetapi tidak menggantikan screening dari perusahaan atau client.", ["Tampilkan proses dan peranmu, bukan hanya gambar akhir.", "Periksa kebutuhan Pro pada aplikasi freelance sebelum mengeluarkan biaya."], ["dribbble", "99designs", "contra"]],
  "yc-work-at-a-startup": ["Ekosistem startup YC", "Profil → peran startup", "Work at a Startup berfokus pada perusahaan dalam ekosistem Y Combinator. Fokus tersebut memudahkan riset tim, tetapi tidak berarti semua perusahaan memiliki kebutuhan atau kondisi kerja yang sama.", ["Pelajari perusahaan", "Pilih peran", "Kirim profil"], "Gunakan profil kandidat atau jalur aplikasi pada peran. Teliti lokasi, kebutuhan pengalaman, dan bentuk kerja sebelum menghubungi tim.", ["Baca produk dan kebutuhan startup sebelum mengirim aplikasi.", "Bedakan remote global dari remote yang dibatasi wilayah."], ["wellfound", "arc", "linkedin-jobs"]],
  freelancer: ["Bidding proyek", "Bid → milestone", "Freelancer menyediakan proyek, bidding, dan kontes dalam satu marketplace. Proyek dan kontes memiliki risiko waktu serta struktur pembayaran berbeda; pilih model sebelum mengalokasikan usaha.", ["Pilih brief", "Hitung bid & fee", "Sepakati milestone"], "Freelancer mengirim bid pada proyek dan menyepakati pekerjaan dengan client. Jumlah bid, saldo minimum, fee proyek, serta opsi membership perlu masuk perhitungan biaya akuisisi.", ["Periksa saldo minimum sebelum mencoba bidding.", "Untuk kontes, batasi waktu eksplorasi karena submission tidak otomatis menghasilkan pembayaran."], ["upwork", "peopleperhour", "fiverr"]],
  toptal: ["Talent network tersaring", "Screening → matching", "Toptal merupakan jaringan talent dengan proses seleksi sebelum peluang client. Ia lebih sesuai sebagai kanal untuk profesional yang sudah punya rekam kerja dan siap menunjukkan keahlian melalui screening.", ["Ajukan profil", "Jalani screening", "Cocokkan proyek"], "Akses peluang mengikuti penerimaan ke jaringan dan kecocokan kebutuhan client. Masuk jaringan tidak sama dengan langsung mendapat engagement; ketersediaan dan model pembayaran perlu dikonfirmasi pada proses resmi.", ["Siapkan contoh keputusan teknis atau desain dari proyek nyata.", "Tanyakan tahap screening, ketersediaan jalur aplikasi, dan ketentuan engagement terbaru."], ["arc", "gun-io", "upwork"]],
  nodesk: ["Listing remote publik", "Cari listing → aplikasi", "NoDesk menyediakan papan kerja dan informasi remote dengan browsing publik. Gunakan kategori serta lokasi untuk menemukan peran yang sesuai, lalu lanjutkan ke proses perusahaan.", ["Pilih kategori", "Verifikasi wilayah", "Lamar ke perusahaan"], "Board membantu menemukan perusahaan; CV, interview, dan kontrak berada dalam alur pemberi kerja. Fitur atau layanan pihak ketiga yang ditautkan memiliki ketentuan terpisah dari akses job board.", ["Utamakan listing dengan cakupan wilayah yang jelas.", "Pastikan tautan aplikasi mengarah ke perusahaan yang sama."], ["himalayas", "jobspresso", "remote-ok"]],
  dribbble: ["Portfolio & hiring kreatif", "Profil / listing → percakapan", "Dribbble memadukan presentasi karya, discovery designer, dan job board. Listing pekerjaan dan jasa freelance adalah jalur berbeda yang memerlukan informasi portfolio serta ketersediaan yang jelas.", ["Tampilkan karya", "Pilih jalur", "Bahas scope"], "Profil dapat menjadi titik awal discovery, sementara listing memiliki proses aplikasi tersendiri. Fitur visibilitas dan leads pada Pro perlu dinilai dari kebutuhanmu; jangkauan tambahan bukan jaminan client.", ["Tautkan shot ke studi kasus agar keputusan desain dapat dipahami.", "Bandingkan fitur Free dan Pro sebelum membeli peningkatan visibilitas."], ["behance-jobs", "contra", "99designs"]],
  "99designs": ["Kontes & proyek 1-to-1", "Kontes / matching → proyek", "99designs menghubungkan designer dengan kontes dan proyek langsung. Bedakan eksplorasi kontes yang belum tentu dibayar dengan engagement 1-to-1 yang memiliki quote serta lingkup kerja disepakati.", ["Siapkan portfolio", "Pilih model kerja", "Quote & handover"], "Designer mengikuti ketentuan penerimaan dan level platform. Untuk proyek langsung, fee platform serta client introduction perlu dihitung; untuk kontes, pahami hadiah dan ketentuan handover sebelum mengerjakan submission.", ["Hitung biaya introduction client baru di dalam quote.", "Tetapkan batas waktu untuk kontes dan periksa hak atas desain."], ["dribbble", "behance-jobs", "contra"]],
  arc: ["Talent & matching remote", "Profil → vetting / interview", "Arc mempertemukan talent dengan peluang freelance dan full-time. Jalur vetting berfokus pada komunikasi serta keahlian; kandidat tetap perlu menilai kecocokan perusahaan dan jam kerja.", ["Buat profil", "Tunjukkan keahlian", "Interview perusahaan"], "Profil, rekomendasi peluang, dan jalur vetting membantu perusahaan memahami pengalamanmu. Arc menyebut profesional berpengalaman dengan komunikasi Inggris yang baik lebih sesuai untuk vetting; proses hiring tetap melibatkan perusahaan.", ["Siapkan cerita singkat tentang keputusan dan hasil proyekmu.", "Tentukan jam overlap dan ketersediaan kontrak secara realistis."], ["toptal", "gun-io", "wellfound"]],
  "gun-io": ["Developer network", "Screening → matching", "Gun.io berfokus pada developer yang melalui pemeriksaan profil dan teknis. Peluangnya mencakup engagement kontrak dan hiring; proses komunikasi serta pembayaran diatur melalui platform.", ["Lengkapi profil", "Jalani evaluasi", "Sepakati engagement"], "Profil perlu disetujui sebelum ditampilkan sebagai kandidat untuk client. FAQ menjelaskan technical interview, koordinasi interview client, serta pembayaran kontrak mingguan dengan ketentuan net 30.", ["Jelaskan kontribusi individu dalam proyek tim secara spesifik.", "Periksa jadwal pembayaran pertama dan aturan komunikasi sebelum engagement."], ["toptal", "arc", "upwork"]],
  "linkedin-jobs": ["Jaringan & job search", "Profil → Easy Apply / ATS", "LinkedIn Jobs menghubungkan pencarian peran dengan profil profesional dan jaringan. Peluang remote bercampur dengan hybrid serta on-site, jadi lokasi dan model kerja perlu disaring secara eksplisit.", ["Rapikan profil", "Saring remote", "Ikuti aplikasi"], "Sebagian peran menerima aplikasi di LinkedIn; lainnya menuju situs perusahaan. Preferensi pekerjaan serta profil memengaruhi rekomendasi, sementara Premium memberikan fitur tambahan yang tidak menjamin hasil hiring.", ["Cocokkan headline dan pengalaman dengan fungsi kerja yang dicari.", "Verifikasi profil perekrut dan domain perusahaan sebelum mengirim dokumen sensitif."], ["wellfound", "nodesk", "himalayas"]],
};

export function editorialFor(slug: string, isBoard: boolean): PlatformEditorial {
  const d = details[slug];
  if (!d) throw new Error(`Missing platform editorial: ${slug}`);
  return { model: d[0], opportunityMethod: d[1], longDescription: d[2], workflow: d[3], workingNotes: d[4], tips: d[5], alternativePlatformSlugs: d[6],
    indonesiaNotes: isBoard ? ["Label remote atau cakupan internasional tidak otomatis membuka posisi bagi pelamar dari Indonesia. Cari syarat negara, izin kerja, dan jam overlap pada listing; konfirmasi jika tidak disebutkan.", "Pembayaran dan bentuk hubungan kerja mengikuti perusahaan. Sebelum menerima offer, tanyakan mata uang, jadwal pembayaran, serta apakah kontraknya employment atau independent contractor."] : ["Akses dan penerimaan talent dari Indonesia belum diverifikasi melalui akun lokal dalam kurasi ini. Konfirmasi negara yang didukung, pemeriksaan identitas, serta metode pencairan dengan platform sebelum membuat komitmen.", "Siapkan komunikasi yang sesuai bahasa client dan tuliskan zona waktu serta jam kerja. Periksa biaya konversi, nama pemilik rekening, dan ketentuan pencairan; metode yang tersedia bisa berbeda menurut negara."] };
}
