import { editorialFor, type PlatformEditorial } from "./freelance-platform-details";
import logos from "./platform-logos.json";
export interface FreelancePlatform extends PlatformEditorial {
  slug: string; name: string; description: string; website: string;
  type: string; categories: string[]; regions: string[]; pricing: "Gratis" | "Freemium" | "Berbayar" | "Periksa ketentuan";
  pricingNote: string; opportunityTypes: string[]; experienceLevels: string[];
  personallyTested: boolean; status: string; lastCheckedAt: string;
  howItWorks: string; forWhom: string; pros: string[]; considerations: string[];
  startSteps: string[]; notes: string; sources: { label: string; url: string }[];
  logo?: { path: string; source: string };
  affiliate: { status: "none" | "available" | "pending" | "active"; affiliateUrl?: string; verifiedAt?: string; disclosureRequired: boolean };
}
type Seed = Pick<FreelancePlatform, "slug" | "name" | "description" | "website" | "type" | "categories" | "pricing" | "pricingNote" | "opportunityTypes" | "howItWorks" | "forWhom" | "pros" | "considerations"> & { source: string; checkedAt?: string };
function platform(seed: Seed): FreelancePlatform {
  const { source, checkedAt, ...data } = seed;
  const editorial = editorialFor(seed.slug, seed.type.includes("Job Board"));
  const logo = (logos as Record<string, { path: string; source: string }>)[seed.slug];
  return { ...data, ...editorial, logo, affiliate: { status: "none", disclosureRequired: false }, regions: ["Internasional"], experienceLevels: [seed.type === "Talent Network" ? "Berpengalaman" : "Beragam"], personallyTested: false,
    status: "Belum dicoba", lastCheckedAt: checkedAt ?? "2026-10-02",
    startSteps: [`Pelajari ${seed.name} melalui sumber resmi di bawah; cek negara dan jalur akses yang tersedia.`, `Siapkan bukti karya untuk ${seed.categories.slice(0, 2).join(" atau ").toLowerCase()}: jelaskan peranmu, proses, dan hasil.`, `Mulai dari ${editorial.workflow[0].toLowerCase()}; lanjutkan sesuai petunjuk resmi platform.`, "Periksa scope, biaya, lokasi, dan jadwal kerja sebelum mengirim aplikasi atau penawaran.", "Catat respons serta hal yang perlu diperbaiki. Evaluasi pendekatan sebelum menambah aplikasi atau membeli fitur tambahan."],
    notes: "Ringkasan berdasarkan informasi publik dari platform, bukan pengalaman penggunaan langsung atau jaminan diterima. Cakupan internasional tidak berarti setiap peluang menerima pelamar dari Indonesia. Level mengikuti persyaratan masing-masing listing.",
    sources: [{ label: "Informasi resmi platform", url: source }, ...(source !== seed.website ? [{ label: "Situs resmi & cara kerja", url: seed.website }] : [])] };
}
export const FREELANCE_PLATFORMS: FreelancePlatform[] = [
  platform({ slug: "we-work-remotely", name: "We Work Remotely", website: "https://weworkremotely.com", type: "Remote Job Board", categories: ["Development", "Design", "Marketing", "Customer Support"], pricing: "Freemium", pricingNote: "Basic gratis untuk menjelajah dan menyimpan. Aplikasi tanpa batas memerlukan Pro; sebagian listing mengizinkan aplikasi langsung. Periksa komitmen dan pembaruan langganan.", opportunityTypes: ["Full-time", "Contract"], description: "Papan peluang remote lintas bidang dengan filter wilayah dan kategori.", howItWorks: "Buat akun, pilih wilayah dan kategori, lalu baca persyaratan dan jalur aplikasi pada listing.", forWhom: "Pencari peran remote yang siap menyaring batasan negara dan zona waktu.", pros: ["Kategori remote yang mudah ditelusuri.", "Preferensi wilayah membantu mempersempit pencarian."], considerations: ["Remote tetap dapat dibatasi negara atau zona waktu.", "Akses aplikasi bergantung pada listing dan paket akun."], source: "https://weworkremotely.com/frequently-asked-questions" }),
  platform({ slug: "contra", name: "Contra", website: "https://contra.com", type: "Freelance Platform", categories: ["Design", "Development", "Writing", "Marketing"], pricing: "Freemium", pricingNote: "Ada paket Free dan Pro. Klaim tanpa komisi tidak berarti semua transaksi bebas biaya: pembayaran client, metode pencairan, dan penyedia pembayaran dapat dikenai biaya.", opportunityTypes: ["Freelance", "Contract"], description: "Profil karya, peluang independen, kontrak, dan pembayaran dalam satu platform.", howItWorks: "Tampilkan proyek di profil, temukan peluang kontrak, dan kelola kesepakatan serta pembayaran melalui platform.", forWhom: "Profesional independen yang ingin menjadikan karya sebagai titik awal percakapan client.", pros: ["Profil berorientasi karya.", "Kontrak dan pembayaran tersedia dalam alur yang sama."], considerations: ["Peluang dan visibilitas berbeda antara Free dan Pro.", "Baca biaya transaksi serta pencairan sesuai metode yang dipakai."], source: "https://contra.com/pricing" }),
  platform({ slug: "problogger", name: "ProBlogger", website: "https://problogger.com/jobs/", type: "Writing Job Board", categories: ["Writing", "Marketing"], pricing: "Gratis", pricingNote: "Menelusuri job board tersedia gratis. Ketentuan kontrak dan pembayaran ditentukan pemberi kerja.", opportunityTypes: ["Freelance", "Contract"], description: "Job board khusus penulisan blog, konten, dan kebutuhan editorial.", howItWorks: "Cari brief penulisan lalu ikuti petunjuk aplikasi dari pengiklan; kontrak dibuat dengan pemberi kerja.", forWhom: "Writer yang memiliki sampel tulisan dan mampu menilai kecocokan niche serta brief.", pros: ["Fokus penulisan memudahkan pencarian niche.", "Brief dapat menjadi bahan riset kebutuhan pasar."], considerations: ["Kualitas brief dan anggaran berbeda-beda.", "Periksa identitas pengiklan, hak atas karya, dan ketentuan revisi."], source: "https://problogger.com/jobs/" }),
  platform({ slug: "upwork", name: "Upwork", website: "https://www.upwork.com", type: "Freelance Platform", categories: ["Development", "Design", "Writing", "Marketing", "Data"], pricing: "Freemium", pricingNote: "Akun dasar tersedia; banyak proposal memakai Connects. Pendapatan kontrak dikenai service fee sesuai ketentuan yang ditampilkan platform.", opportunityTypes: ["Freelance", "Contract"], description: "Marketplace proyek dengan proposal, kontrak per jam, dan proyek berbasis milestone.", howItWorks: "Lengkapi profil, pilih proyek, kirim proposal dengan Connects bila diperlukan, lalu sepakati kontrak.", forWhom: "Freelancer yang siap menulis proposal spesifik dan menghitung biaya akuisisi client.", pros: ["Model kontrak per jam dan fixed-price.", "Banyak kategori jasa dalam satu marketplace."], considerations: ["Connects tidak menjamin proposal dibaca atau diterima.", "Hitung service fee sebelum menyepakati rate."], source: "https://support.upwork.com/hc/en-us/articles/211062898-Understanding-and-using-Connects" }),
  platform({ slug: "fiverr", name: "Fiverr", website: "https://www.fiverr.com", type: "Freelance Platform", categories: ["Design", "Writing", "Development", "Marketing"], pricing: "Freemium", pricingNote: "Freelancer menerima 80% nilai pesanan menurut halaman Earnings resmi. Periksa biaya pencairan dan program tambahan.", opportunityTypes: ["Freelance"], description: "Marketplace jasa yang dikemas sebagai offer atau Gig dengan lingkup yang jelas.", howItWorks: "Publikasikan Gig, jelaskan deliverable dan paket, lalu kerjakan pesanan sesuai kesepakatan.", forWhom: "Freelancer dengan layanan yang bisa dikemas menjadi paket terukur.", pros: ["Format Gig membantu memperjelas scope.", "Paket jasa dapat menampilkan beberapa pilihan deliverable."], considerations: ["Potongan pendapatan harus masuk perhitungan harga.", "Tentukan batas revisi dan detail paket dengan teliti."], source: "https://help.fiverr.com/hc/en-us/articles/9234443621137-Your-earnings-page" }),
  platform({ slug: "peopleperhour", name: "PeoplePerHour", website: "https://www.peopleperhour.com", type: "Freelance Platform", categories: ["Design", "Development", "Writing", "Marketing"], pricing: "Freemium", pricingNote: "Pendaftaran, pencarian proyek, dan publikasi offer tanpa biaya. Service fee dikenakan pada pendapatan; cek tarif resmi sebelum menetapkan harga.", opportunityTypes: ["Freelance", "Contract"], description: "Marketplace proyek dan offer untuk jasa per jam maupun per proyek.", howItWorks: "Bangun profil, kirim proposal proyek atau publikasikan offer, dan gunakan WorkStream untuk komunikasi proyek.", forWhom: "Freelancer yang ingin menggabungkan proposal custom dan paket jasa.", pros: ["Pilihan proposal dan offer.", "Percakapan serta riwayat proyek dalam WorkStream."], considerations: ["Service fee memengaruhi pendapatan bersih.", "Periksa kebijakan offer dan proses penerimaan profil."], source: "https://support.peopleperhour.com/hc/en-us/articles/205218337-Freelancer-commission-fees" }),
  platform({ slug: "remote-ok", name: "Remote OK", website: "https://remoteok.com", type: "Remote Job Board", categories: ["Development", "Design", "Marketing", "Customer Support"], pricing: "Freemium", pricingNote: "Ada listing dan feed publik, serta fitur Premium dan TopAccess. Detail akses dan biaya perlu diperiksa pada FAQ resmi.", opportunityTypes: ["Full-time", "Contract"], description: "Papan pekerjaan dengan tag skill, lokasi, dan kategori remote.", howItWorks: "Saring tag dan lokasi, baca deskripsi lengkap, lalu ikuti tautan aplikasi perusahaan.", forWhom: "Pencari kerja yang ingin menelusuri peran berdasarkan skill teknis atau fungsi kerja.", pros: ["Tag skill untuk penelusuran cepat.", "Informasi lokasi pada listing."], considerations: ["Sebagian informasi atau fitur berada di paket berbayar.", "Selalu verifikasi listing pada situs perusahaan."], source: "https://remoteok.com/faq" }),
  platform({ slug: "remotive", name: "Remotive", website: "https://remotive.com", type: "Remote Job Board", categories: ["Development", "Design", "Marketing", "Customer Support"], pricing: "Berbayar", pricingNote: "Akses pencarian penuh berbayar; informasi publik dapat terbatas. Baca paket dan aturan langganan terbaru sebelum membayar.", opportunityTypes: ["Full-time", "Contract"], description: "Pencarian pekerjaan remote dengan kategori dan informasi lokasi.", howItWorks: "Cari peran yang sesuai dan ikuti tautan aplikasi ke halaman karier perusahaan.", forWhom: "Pencari kerja yang bersedia membayar akses kurasi dan memeriksa kecocokan lokasi.", pros: ["Kategori dan lokasi membantu pencarian.", "Aplikasi diarahkan ke perusahaan."], considerations: ["Langganan tidak menjamin pekerjaan.", "Waspadai pihak yang mengatasnamakan Remotive melalui pesan pribadi."], source: "https://support.remotive.com/en/article/frequently-asked-questions-180nrek/" }),
  platform({ slug: "flexjobs", name: "FlexJobs", website: "https://www.flexjobs.com", type: "Flexible Job Board", categories: ["Writing", "Development", "Marketing", "Customer Support"], pricing: "Berbayar", pricingNote: "Akses penuh memakai langganan. Paket percobaan dapat berlanjut otomatis; periksa harga, periode, dan pembatalannya.", opportunityTypes: ["Full-time", "Part-time", "Contract"], description: "Peluang remote, hybrid, dan kerja fleksibel dengan akses berlangganan.", howItWorks: "Pilih paket lalu saring pekerjaan berdasarkan kebutuhan; baca lokasi dan model kerja setiap listing.", forWhom: "Pencari kerja yang mempertimbangkan remote maupun jadwal fleksibel.", pros: ["Mencakup beberapa model kerja fleksibel.", "Platform menyatakan melakukan penyaringan listing."], considerations: ["Tidak semua pekerjaan sepenuhnya remote.", "Perhatikan pembaruan otomatis dan total biaya langganan."], source: "https://www.flexjobs.com/pricing" }),
  platform({ slug: "wellfound", name: "Wellfound", website: "https://wellfound.com", type: "Startup Job Board", categories: ["Development", "Product", "Design", "Marketing"], pricing: "Gratis", pricingNote: "Membuat profil dan melamar gratis untuk kandidat menurut FAQ resmi.", opportunityTypes: ["Full-time"], description: "Peluang startup dan teknologi dengan profil kandidat serta informasi kompensasi.", howItWorks: "Buat profil, tetapkan preferensi peran dan lokasi, lalu kirim aplikasi ke startup yang sesuai.", forWhom: "Kandidat yang ingin bekerja di lingkungan startup dan menilai tahap serta kebutuhan tim.", pros: ["Profil dapat digunakan untuk beberapa aplikasi.", "Informasi salary dan equity pada banyak listing."], considerations: ["Pekerjaan remote dan on-site bercampur.", "Kebutuhan serta risiko startup berbeda menurut tahap perusahaan."], source: "https://wellfound.com/candidates/overview" }),
  platform({ slug: "himalayas", name: "Himalayas", website: "https://himalayas.app", type: "Remote Job Board", categories: ["Development", "Design", "Marketing", "Customer Support"], pricing: "Freemium", pricingNote: "Profil, browsing, dan aplikasi gratis. Plus dan Max menawarkan fitur tambahan berbayar.", opportunityTypes: ["Full-time", "Contract"], description: "Pencarian remote dengan preferensi negara, zona waktu, dan profil perusahaan.", howItWorks: "Tetapkan lokasi serta preferensi, cari listing, dan gunakan profil atau petunjuk aplikasi perusahaan.", forWhom: "Pencari kerja yang perlu menyaring kesesuaian zona waktu dan negara sejak awal.", pros: ["Filter negara dan zona waktu.", "Fitur dasar pencarian dan aplikasi gratis."], considerations: ["Fitur AI tertentu memerlukan paket tambahan.", "Keputusan hiring berada pada perusahaan, bukan platform."], source: "https://himalayas.app/docs/what-is-himalayas" }),
  platform({ slug: "working-nomads", name: "Working Nomads", website: "https://www.workingnomads.com/jobs", type: "Remote Job Board", categories: ["Development", "Design", "Marketing", "Data"], pricing: "Freemium", pricingNote: "Listing publik gratis; Premium membuka lebih banyak listing, filter, dan alert.", opportunityTypes: ["Full-time", "Part-time", "Contract"], description: "Kurasi peluang remote lintas fungsi dengan pilihan alert dan akses Premium.", howItWorks: "Jelajahi listing publik berdasarkan kategori atau gunakan fitur Premium jika diperlukan.", forWhom: "Pencari peran remote yang ingin menata pencarian berdasarkan fungsi kerja.", pros: ["Kategori lintas fungsi.", "Listing publik tersedia sebelum berlangganan."], considerations: ["Sebagian listing dan filter berada di Premium.", "Periksa negara yang diterima pada setiap peran."], source: "https://www.workingnomads.com/premium-subscription" }),
  platform({ slug: "jobspresso", name: "Jobspresso", website: "https://jobspresso.co", type: "Remote Job Board", categories: ["Development", "Marketing", "Customer Support"], pricing: "Gratis", pricingNote: "Gratis bagi pencari kerja menurut FAQ resmi.", opportunityTypes: ["Full-time", "Contract"], description: "Job board remote untuk peran teknologi, marketing, dan support.", howItWorks: "Telusuri kategori pekerjaan lalu ikuti petunjuk aplikasi; profil resume juga tersedia.", forWhom: "Pencari kerja yang ingin menelusuri board remote tanpa langganan kandidat.", pros: ["Akses gratis bagi pencari kerja.", "Platform menyatakan meninjau pengiklan dan listing."], considerations: ["Zona waktu atau kunjungan kantor tetap dapat disyaratkan.", "Periksa keaktifan listing sebelum melamar."], source: "https://jobspresso.co/faq/" }),
  platform({ slug: "behance-jobs", name: "Behance Jobs", website: "https://www.behance.net/joblist", type: "Creative Job Board", categories: ["Design", "Writing"], pricing: "Freemium", pricingNote: "Browsing dan aplikasi full-time gratis. Aplikasi freelance memerlukan Behance Pro menurut pembaruan job board Juni 2026.", opportunityTypes: ["Full-time", "Freelance"], description: "Peluang kreatif yang terhubung dengan ekosistem portfolio Behance.", howItWorks: "Gunakan portfolio, saring bidang kreatif dan lokasi, lalu cek jalur aplikasi serta kebutuhan Pro.", forWhom: "Profesional kreatif dengan portfolio visual yang sudah siap ditampilkan.", pros: ["Portfolio dan peluang kreatif saling terhubung.", "Filter freelance, full-time, dan lokasi."], considerations: ["Remote, hybrid, dan on-site bercampur.", "Aplikasi freelance memerlukan paket Pro."], source: "https://www.behance.net/blog/new-job-board" }),
  platform({ slug: "yc-work-at-a-startup", name: "YC Work at a Startup", website: "https://www.ycombinator.com/jobs/", type: "Startup Job Board", categories: ["Development", "Product", "Design", "Marketing"], pricing: "Gratis", pricingNote: "Listing dapat ditelusuri secara publik. Periksa ketentuan akun kandidat pada situs resmi.", opportunityTypes: ["Full-time"], description: "Pencarian pekerjaan di perusahaan dalam ekosistem Y Combinator.", howItWorks: "Cari perusahaan dan peran, periksa lokasi, lalu gunakan profil kandidat atau jalur aplikasi yang tersedia.", forWhom: "Kandidat yang ingin mempelajari kebutuhan tim startup dalam ekosistem YC.", pros: ["Fokus pada ekosistem perusahaan YC.", "Profil kandidat dapat dipakai untuk menjelajahi peluang."], considerations: ["Tidak semua peran remote.", "Syarat lokasi dan pengalaman mengikuti perusahaan."], source: "https://www.ycombinator.com/jobs/" }),
  platform({ slug: "freelancer", name: "Freelancer", website: "https://www.freelancer.com", type: "Freelance Platform", categories: ["Development", "Design", "Writing", "Marketing", "Data"], pricing: "Freemium", pricingNote: "Pendaftaran dasar gratis. Fixed-price dikenai 10% atau US$5, mana yang lebih besar; hourly 10%. Ada batas bid, saldo minimum sebelum bidding, membership, dan biaya lain. Baca tabel resmi sebelum menerima proyek.", opportunityTypes: ["Freelance", "Contract"], description: "Marketplace dengan bidding proyek, milestone, serta kontes lintas bidang.", howItWorks: "Buat profil, baca proyek, kirim bid, lalu sepakati milestone atau ikuti ketentuan kontes.", forWhom: "Freelancer yang siap menilai brief, menulis bid, dan menghitung biaya proyek.", pros: ["Pilihan proyek dan kontes dalam satu platform.", "Milestone dapat memisahkan pekerjaan menjadi deliverable."], considerations: ["Ada saldo minimum sebelum bidding; periksa angka yang ditampilkan pada akun.", "Kontes tidak menjamin semua peserta dibayar."], source: "https://www.freelancer.com/feesandcharges", checkedAt: "2026-10-03" }),
  platform({ slug: "toptal", name: "Toptal", website: "https://www.toptal.com/freelance-jobs", type: "Talent Network", categories: ["Development", "Design", "Product", "Management"], pricing: "Periksa ketentuan", pricingNote: "FAQ membahas rate dan pembayaran talent, tetapi tidak memberikan satu daftar biaya kandidat yang lengkap. Konfirmasi ketentuan screening, akses, dan engagement terbaru; kurasi ini tidak menyimpulkan semua tahap gratis.", opportunityTypes: ["Freelance", "Contract"], description: "Jaringan talent dengan screening dan pencocokan kebutuhan proyek client.", howItWorks: "Ajukan profil, jalani proses screening, lalu ikuti peluang atau matching setelah diterima.", forWhom: "Profesional berpengalaman yang siap menjalani evaluasi keahlian dan komunikasi.", pros: ["Matching berorientasi skill dan kebutuhan client.", "Kategori mencakup teknologi, desain, serta peran manajemen."], considerations: ["Penerimaan dan ketersediaan peluang tidak dijamin.", "FAQ menyebut pengalaman beberapa tahun untuk jalur aplikasi talent."], source: "https://www.toptal.com/freelance-jobs/faq", checkedAt: "2026-10-03" }),
  platform({ slug: "nodesk", name: "NoDesk", website: "https://nodesk.co/remote-jobs/", type: "Remote Job Board", categories: ["Development", "Design", "Marketing", "Customer Support"], pricing: "Gratis", pricingNote: "Job board publik dapat ditelusuri dan digunakan untuk aplikasi gratis. Layanan pihak ketiga yang ditautkan, termasuk otomasi, memiliki ketentuan terpisah.", opportunityTypes: ["Full-time", "Contract"], description: "Papan kerja remote publik dengan kategori, lokasi, dan informasi perusahaan.", howItWorks: "Telusuri kategori, cek wilayah yang diterima, lalu ikuti tautan aplikasi perusahaan.", forWhom: "Pencari peran remote yang ingin memulai riset melalui listing publik.", pros: ["Browsing job board tanpa biaya kandidat.", "Kategori dan lokasi membantu penelusuran."], considerations: ["Lokasi dan syarat kerja mengikuti perusahaan.", "Periksa tanggal serta sumber listing sebelum melamar."], source: "https://nodesk.co/remote-jobs/", checkedAt: "2026-10-03" }),
  platform({ slug: "dribbble", name: "Dribbble", website: "https://dribbble.com/jobs", type: "Creative Job Board", categories: ["Design", "Product"], pricing: "Freemium", pricingNote: "Ada profil Free serta paket Pro untuk fitur discovery dan leads tambahan. Fee dan benefit pembayaran berbeda menurut paket; periksa perbandingan resmi, termasuk syarat annual plan.", opportunityTypes: ["Full-time", "Part-time", "Freelance", "Contract"], description: "Portfolio designer, job board, dan discovery jasa kreatif dalam satu ekosistem.", howItWorks: "Tampilkan karya, jelajahi listing desain atau discovery jasa, lalu bahas kebutuhan dan proses aplikasi.", forWhom: "Designer dengan portfolio visual yang dapat menjelaskan konteks serta kontribusi proyek.", pros: ["Karya dan profil dapat menjadi titik awal discovery.", "Listing mencakup beberapa model kerja kreatif."], considerations: ["Remote, hybrid, dan on-site dapat bercampur.", "Visibilitas Pro tidak menjamin leads berubah menjadi client."], source: "https://dribbble.com/pro", checkedAt: "2026-10-03" }),
  platform({ slug: "99designs", name: "99designs", website: "https://99designs.com/designers", type: "Freelance Platform", categories: ["Design"], pricing: "Freemium", pricingNote: "Pendaftaran gratis; proyek 1-to-1 dikenai fee designer 5–15% menurut level. Client introduction mengenakan 20% dari US$500 pertama dengan client baru, maksimum US$100, dengan pengecualian tertentu. Metode pencairan dapat memiliki biaya tambahan.", opportunityTypes: ["Freelance"], description: "Peluang desain melalui kontes dan proyek langsung 1-to-1 dengan client.", howItWorks: "Ajukan profil designer, pilih kontes atau proyek langsung, dan ikuti aturan quote serta handover.", forWhom: "Designer yang memahami perbedaan risiko kontes dan kontrak proyek langsung.", pros: ["Model kontes dan proyek 1-to-1.", "Level designer membedakan fee pada proyek langsung."], considerations: ["Submission kontes tidak otomatis dibayar.", "Fee introduction dan platform perlu dihitung bersama."], source: "https://support.99designs.com/hc/en-us/articles/204761265-What-fees-do-you-charge-for-1-to-1-Projects", checkedAt: "2026-10-03" }),
  platform({ slug: "arc", name: "Arc", website: "https://arc.dev/talent", type: "Talent Network", categories: ["Development", "Design", "Marketing", "Product"], pricing: "Gratis", pricingNote: "Halaman talent menyatakan penggunaan platform gratis bagi kandidat, termasuk saat mendapat pekerjaan. Ketentuan kontrak, rate, serta metode pembayaran tetap perlu dikonfirmasi untuk engagement yang ditawarkan.", opportunityTypes: ["Freelance", "Full-time", "Contract"], description: "Profil talent, vetting, dan matching untuk pekerjaan freelance maupun full-time remote.", howItWorks: "Buat profil, ikuti jalur vetting yang relevan, lalu interview dengan perusahaan yang cocok.", forWhom: "Profesional yang dapat menunjukkan keahlian dan berkomunikasi dengan tim internasional.", pros: ["Peluang freelance dan full-time.", "Vetting menilai komunikasi serta keahlian."], considerations: ["Vetting lebih sesuai untuk profesional berpengalaman menurut platform.", "Kecocokan lokasi dan jam kerja tetap mengikuti perusahaan."], source: "https://arc.dev/talent", checkedAt: "2026-10-03" }),
  platform({ slug: "gun-io", name: "Gun.io", website: "https://gun.io", type: "Talent Network", categories: ["Development"], pricing: "Periksa ketentuan", pricingNote: "FAQ menyatakan developer dibayar sesuai rate yang diminta. Kurasi belum memverifikasi daftar lengkap biaya kandidat dan pencairan. Untuk kontrak, FAQ menjelaskan pembayaran mingguan dengan net 30; konfirmasi detail engagement sebelum menerima.", opportunityTypes: ["Contract", "Full-time"], description: "Jaringan developer dengan evaluasi teknis serta koordinasi kontrak dan hiring.", howItWorks: "Lengkapi profil, jalani screening serta technical interview, lalu ikuti matching dan interview client.", forWhom: "Developer berpengalaman yang siap menunjukkan rekam kerja dan keputusan teknis.", pros: ["Koordinasi interview dan engagement melalui platform.", "Penagihan serta pembayaran kontrak dikelola dalam alur platform."], considerations: ["Profil perlu disetujui sebelum masuk shortlist client.", "Aturan komunikasi sebelum kontrak dan jadwal pembayaran perlu dipahami."], source: "https://gun.io/faq/", checkedAt: "2026-10-03" }),
  platform({ slug: "linkedin-jobs", name: "LinkedIn Jobs", website: "https://www.linkedin.com/jobs/", type: "General Job Board", categories: ["Development", "Design", "Writing", "Marketing", "Management"], pricing: "Freemium", pricingNote: "Akun Basic gratis untuk fitur dasar pencarian dan profil. Premium menambah fitur kandidat; kebutuhan upgrade berbeda menurut fitur dan tidak menjamin diterima bekerja.", opportunityTypes: ["Full-time", "Part-time", "Contract"], description: "Pencarian pekerjaan yang terhubung dengan profil profesional dan jaringan perusahaan.", howItWorks: "Saring lokasi dan remote, lalu gunakan Easy Apply atau jalur aplikasi pada situs perusahaan.", forWhom: "Kandidat yang ingin menggabungkan pencarian peran, riset perusahaan, dan jaringan profesional.", pros: ["Profil serta preferensi membantu pencarian peran.", "Ada jalur aplikasi di platform maupun situs perusahaan."], considerations: ["Tidak semua listing remote atau terbuka lintas negara.", "Verifikasi identitas perekrut dan pengaturan privasi profil."], source: "https://www.linkedin.com/help/linkedin/answer/a512279/", checkedAt: "2026-10-03" }),
];

// Each dated source remains attributable; editorial tips do not imply hands-on testing.
const extraSources: Record<string, { label: string; url: string }[]> = {
  upwork: [{ label: "Service fee freelancer", url: "https://support.upwork.com/hc/en-us/articles/211062538-Learn-about-the-Freelancer-Service-Fee" }],
  "99designs": [{ label: "Client introduction fee", url: "https://support.99designs.com/hc/en-us/articles/360022018152-What-is-a-client-introduction-fee" }, { label: "Pembayaran & metode per negara", url: "https://support.99designs.com/hc/en-us/articles/204108819-How-and-when-do-I-get-paid" }],
  "linkedin-jobs": [{ label: "Pencarian & aplikasi pekerjaan", url: "https://www.linkedin.com/help/linkedin/topic/a153003?lang=en" }],
};
for (const p of FREELANCE_PLATFORMS) p.sources.push(...(extraSources[p.slug] ?? []));
for (const p of FREELANCE_PLATFORMS) if (["we-work-remotely", "contra", "fiverr", "upwork"].includes(p.slug)) p.lastCheckedAt = "2026-10-03";
const design = FREELANCE_PLATFORMS.find(p => p.slug === "99designs")!;
design.indonesiaNotes[1] = "Halaman payout resmi mewajibkan Hyperwallet dan menyatakan metode transfer berbeda menurut negara. Pilihan yang benar-benar tersedia untuk akun Indonesia perlu diperiksa pada akun resmi; kurasi ini belum menguji pencairan lokal.";

export function platformOutbound(p: FreelancePlatform) {
  const a = p.affiliate;
  const active = a.status === "active" && Boolean(a.verifiedAt && a.affiliateUrl?.startsWith("https://"));
  return { href: active ? a.affiliateUrl! : p.website, affiliate: active, rel: active ? "sponsored noopener noreferrer" : "noopener noreferrer" };
}
export function platformAlternatives(p: FreelancePlatform) {
  return p.alternativePlatformSlugs.map(slug => FREELANCE_PLATFORMS.find(item => item.slug === slug)).filter((item): item is FreelancePlatform => Boolean(item && item.slug !== p.slug));
}
export const FEATURED_PLATFORMS = FREELANCE_PLATFORMS.slice(0, 3);
